# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Cqicd <- function(Y, X, beta_in, tau, intercept, lambda, model, a, threshod, maxint) {
    .Call('_qrLOFT_Cqicd', PACKAGE = 'qrLOFT', Y, X, beta_in, tau, intercept, lambda, model, a, threshod, maxint)
}

.BicVal <- function(Y, X, beta_in, tau, intercept, C) {
    .Call('_qrLOFT_BicVal', PACKAGE = 'qrLOFT', Y, X, beta_in, tau, intercept, C)
}

.PrecisionMat <- function(Xs, Xsc) {
    .Call('_qrLOFT_PrecisionMat', PACKAGE = 'qrLOFT', Xs, Xsc)
}

.MMuhat <- function(Xs, Xsc, Beta) {
    .Call('_qrLOFT_MMuhat', PACKAGE = 'qrLOFT', Xs, Xsc, Beta)
}

.MSighat <- function(Xs, Xsc) {
    .Call('_qrLOFT_MSighat', PACKAGE = 'qrLOFT', Xs, Xsc)
}

.QRlof <- function(X, Y, tau, intercept, B, Cret) {
    .Call('_qrLOFT_QRlof', PACKAGE = 'qrLOFT', X, Y, tau, intercept, B, Cret)
}

qrmm <- function(X, Y, tau) {
    .Call('_qrLOFT_qrmm', PACKAGE = 'qrLOFT', X, Y, tau)
}

